# Site settings
site: Vina Jar
title: Vina Jar - Java Core, Java Framework, Java Tools,...
keywords: java, trannguyenhan
description: >-
  Java Core, Java Framework, Java Tools,...
lang: en-US
timezone:  Asia/Ho_Chi_Minh
repo: https://github.com/vinajar/vinajar.github.io # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: trannguyenhan
  bio: I'm Dev
  picture: assets/images/profile.jpg 
  github: onepase # github username
  twitter: onepase # twitter username
  facebook: onepase # facebook username
  instagram: onepase # instagram username
  youtube: https://www.youtube.com/@tran_nguyenhan # youtube username
  linkedin: trannguyenhan # linkedin username
  email: trannguyenhan01092000@gmail.com # email adress


# URL settings
url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false